### ISSUE TITLE
Missing doc: Required .NET Framework version

### ISSUE THREAD

**Issue by heretic13** [kohsuke/winsw#102]
No description of what is required version of the framework.

**Comment by oleg-nenashev** [comment]
Yes, there is no explicit spec for it in the documentation.
Currently WinSW supports .NET 2.0, but it also can be launched on newer versions. I'm not sure about Compact Framework and other stuff with the reduced functionality.

**Comment by oleg-nenashev** [comment]
Overlaps with #103

**Comment by oleg-nenashev** [comment]
Done
