### ISSUE TITLE
Provide version of winsw targeting .NET Framework 4.0

### ISSUE THREAD

**Issue by matthewadams** [kohsuke/winsw#103]
The fact that winsw currently targets .NET 2.0, which is not installed by default on recent Windows distributions, is causing downstream headaches for consumers of projects like https://github.com/coreybutler/node-windows, which doesn't currently create a `.exe.config` file.

Please modernize a bit and create a distribution that targets .NET 4.0.

**Comment by oleg-nenashev** [comment]
Also the new package needs to be packaged into Jenkins project directly.
https://issues.jenkins-ci.org/browse/JENKINS-31564

**Comment by oleg-nenashev** [comment]
So, I have added the .NET4 packaging in #147. Would appreciate some testing and feedback

**Comment by oleg-nenashev** [comment]
@matthewadams So the .NET4 release is available.
See https://github.com/kohsuke/winsw/releases/tag/winsw-draft-v2.0-SNAPSHOT-build34
