### ISSUE TITLE
Service in inconsistent state

### ISSUE THREAD

**Issue by Lizyaffe** [kohsuke/winsw#104]
After several sequences of registering and removing a service with the same id, I now reached a state where the service no longer appears in the services dialog but I also cannot register it.

When trying to register, getting the following message:
Service with id 'JIService' already exists
To install the service, delete the existing one or change service Id in the configuration file
System.Exception: Installation failure: Service with id 'JIService' already exists
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

**Comment by oleg-nenashev** [comment]
@Lizyaffe 
I suppose there is a non-deleted entry in the registry. Could you check it's contents and attach them to the ticket? 

Some info about services location in the registry: http://smallvoid.com/article/winnt-services-regedit.html

**Comment by oleg-nenashev** [comment]
No response from the requester
