### ISSUE TITLE
Can't run command on CMD

### ISSUE THREAD

**Issue by LeecOVO** [kohsuke/winsw#1056]
### Problem statement
My App have a new feature. Need run some command on CMD(open Explorer) .
When use WinSW to run SpringBoot Project on service.
Java Code: 
  `Runtime.getRuntime().exec(command);`
or
  `Process process = new ProcessBuilder().command(cmd).start();`
Even open Interactive services option. There are not working!
I need your guys help.

**Comment by egan-mw** [comment]
请教下这个问题怎么解决的
