### ISSUE TITLE
No 1.17 or 1.18 release, just tags?

### ISSUE THREAD

**Issue by carlpett** [kohsuke/winsw#107]
Hi,
There are tags for 1.17 and 1.18, but the latest release is 1.17-beta2. Could binary releases be supplied for at least the latest version?

**Comment by oleg-nenashev** [comment]
Hi,

See https://github.com/kohsuke/winsw#download

**Comment by carlpett** [comment]
Ah, thanks. Might be good to make that more prominent - since there were _some_ releases on GitHub, I figured that would be all of them.
