### ISSUE TITLE
rewrite winsw in native code.

### ISSUE THREAD

**Issue by jtnord** [kohsuke/winsw#108]
It's a pain to have to deal with .net - checking it is installed on the machines - and getting it installed automatically is not easy - especially in an automated environment (and even more so in Server 2012+ where you can not even use the bootstrap assemblies).

Also .net 20 is long dead and the SDK won't install on modern windows platforms without jumping through some special hoops.

So lets use unmanaged C++ and statically link in our dependencies!

**Comment by oleg-nenashev** [comment]
Uhm, unmanaged C++ is a bit painful from the implementation scope.
I understand the intention, but I doubt somebody will have enough spare time to completely rework winsw. Outdated .NET version needs to be fixed in any case.

**Comment by jtnord** [comment]
actually writing a service is not rocket science, logging can now use the boost framework, - the xml parsing can use xmllite - so the amount of code needed is not huge.

Given I am not expecting that this is a huge amount of code, leaks can be detected with the inbuilt tooling in Visual studio (apparently - not used it, but I have used a commercial solution in the past on large projects).

so yes a little tounge in cheek but I may get around to this at some point and I don't think it would require an exhaustive amount of work.

**Comment by Spamme1** [comment]
@jtnord use [nssm](https://nssm.cc/)

**Comment by oleg-nenashev** [comment]
@Spamme1 
Maybe be.

Anyway, I have no medium-term plans to trewrite the component. I would like to continue working on WinSW 2.0 branch, but it will still utilize .NET

**Comment by oleg-nenashev** [comment]
Well, it would be another project. Nothin to do in this repo IMHO. No sense to create just another service wrapper.
