### ISSUE TITLE
command "refresh" not working on Ver 2.12.0

### ISSUE THREAD

**Issue by pocketdr** [kohsuke/winsw#1081]
### Problem statement

Is it was a new command on Ver 3.x? Why list a pre-release command on the index page?

**Comment by Lurito** [comment]
Yes. It is a new command for v3. The [master branch](https://github.com/winsw/winsw/tree/master) shows the document of v2.

The default branch of this project is v3, but the release version displayed by default is v2.1.2. This can indeed cause confusion in some cases.

**Comment by pocketdr** [comment]
> Yes. It is a new command for v3. The [master branch](https://github.com/winsw/winsw/tree/master) shows the document of v2.
> 
> The default branch of this project is v3, but the release version displayed by default is v2.1.2. This can indeed cause confusion in some cases.

thx
