### ISSUE TITLE
.Net 4.0 framework release

### ISSUE THREAD

**Issue by ada3000** [kohsuke/winsw#112]
Hi!
Add framework 4.0 build to release, please :)

On modern servers, by default, installed .net 4.0.
Install .net 2.0(3.5) are very difficult.

**Comment by Spiralis** [comment]
You can get around this by configuration by adding a .exe.config file with extra directives: http://www.davidmoore.info/blog/2010/12/17/running-net-2-runtime-applications-under-the-net-4-runtime/.

But, I do agree that having a native .Net 4 build would be good too (better).

**Comment by oleg-nenashev** [comment]
I consider Dropping the .NET 2 support at all in WinSW 2 or 3

**Comment by oleg-nenashev** [comment]
Duplicates #103 BTW

**Comment by oleg-nenashev** [comment]
So, I have added the .NET4 packaging in #147. Would appreciate some testing and feedback

**Comment by oleg-nenashev** [comment]
So the patch has been integrated.
Draft release: https://github.com/kohsuke/winsw/releases/tag/winsw-draft-v2.0-SNAPSHOT-build34
