### ISSUE TITLE
Environment Variable Expansion does not work

### ISSUE THREAD

**Issue by kaldebert** [kohsuke/winsw#113]
When I start the service, this error occurs:

> Service cannot be started. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\windows\system32\%BASE%\logs\project.wrapper.log'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
>    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
>    at System.IO.StreamWriter..ctor(String path, Boolean append)
>    at winsw.WrapperService.WriteEvent(String message)

Here is my XML config file:

```
<service>
    <id>project-id</id>
    <name>project-name</name>
    <description>project-description</description>
    <env name="BASE" value="%PROJECT_HOME%" />
    <workingdirectory>%BASE%\</workingdirectory>
    <logpath>%BASE%\logs</logpath>
    <logmode>rotate</logmode>

    <executable>java</executable>
    <startargument>-cp</startargument>
    <startargument>lib/*</startargument>
    <startargument>com.mycompany.StartService</startargument>

    <stopexecutable>java</stopexecutable>
    <stopargument>-cp</stopargument>
    <stopargument>lib/*</stopargument>
    <stopargument>com.mycompany.StopService</stopargument>
</service>
```

`PROJECT_HOME` is defined as a environment variable and contains the path to the folder project.

OS: Windows Server 2008 R2 SP1
winsw version: 1.9

Why `PROJECT_HOME` is not replaced by the defined path ?

**Comment by oleg-nenashev** [comment]
Sorry for the late response, but your Environment setting assigns the `BASE` environment variable, which is a system-internal one. From what I see it just causes a collision. BTW, maybe there should be an RFE for support of external environment variable in configuration files.
