### ISSUE TITLE
How to keep application running like a daemon

### ISSUE THREAD

**Issue by parasmk** [kohsuke/winsw#118]
I have a need to constantly poll every 60 seconds. How can this be achieved within the installed application such that it can be installed/used by service wrapper?

**Comment by oleg-nenashev** [comment]
Your application should perform such periodic polling. WinSW would just monitor it in such case.

You could try getting launch period by setting up the process failover in WinSW, but it's not the approach I'm ready to recommend.

**Comment by oleg-nenashev** [comment]
Closing since there is no response from the requester
