### ISSUE TITLE
Finalize the winsw 2.0 release

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [kohsuke/winsw#122]
Has the development ceased on this ?

**Comment by oleg-nenashev** [comment]
Well, it's not dead. I was just snowed by zillions of other TODOs in Jenkins community and have never got back to it. I hope to spend some time on it in October

**Comment by rahul-dutt-sharma** [comment]
Ty :)

**Comment by oleg-nenashev** [comment]
BTW, you still can take beta release from https://github.com/kohsuke/winsw/releases/tag/1.17-beta.2

**Comment by oleg-nenashev** [comment]
Scheduled it for my Hacktoberfest

**Comment by oleg-nenashev** [comment]
OK, WinSW 2 is finally released. Took a bit longer, but hopefully now the project is more stable
