### ISSUE TITLE
New plugin: Terminate runaway processes on startup [JENKINS-39231]

### ISSUE THREAD

**Issue by oleg-nenashev** [kohsuke/winsw#125]
In Jenkins projects we have many users complaining that the slave/agent is "already connected", because they have a runaway slave/agent process. It happens when WinSW gets terminated without executing the process shutdown logic (force kill, JVM crash) or when WinSW fails to terminate the process.

As a part of WinSW 2.0, it would be great to create a logic, which...
- records PID of the created process to the disc
- performs status check of the previously spawned process upon restart
- terminates the runaway process if required

It can be done via WinSW 2 "plugin"

https://issues.jenkins-ci.org/browse/JENKINS-39231

**Comment by oleg-nenashev** [comment]
Related Jenkins issues: https://issues.jenkins-ci.org/browse/JENKINS-39231

**Comment by calebboyd** [comment]
This would be really slick if it solves the problem described in #105. We're running hundreds of installations and we see this happen frequently. Need any help here?

**Comment by oleg-nenashev** [comment]
@calebboyd Well, any kinds of testing and reviews would be useful. I have created #133 with the change.

**Comment by oleg-nenashev** [comment]
The pull request has been integrated towards 2.0
