### ISSUE TITLE
winsw restart messes up the service account credentials.

### ISSUE THREAD

**Issue by bdarwin** [kohsuke/winsw#136]
I installed a service 
`winsw install  
`Granted service account credentials manually.
`winsw restart `
This throws Error 1069: The service did not start due to a logon failure.

**Comment by oleg-nenashev** [comment]
What is the problem exactly? Are you sure that account credentials were correct?

**Comment by oleg-nenashev** [comment]
Closing since there is no response from the requester. Feel free to reopen
