### ISSUE TITLE
Deploy Pull request builder for WinSW

### ISSUE THREAD

**Issue by oleg-nenashev** [kohsuke/winsw#142]
The old PR builder is dead. It makes sense to deploy something new using the available toolchains for Windows. I see the following ways:

* Use Visual Studio Team Services
* Get some help from Jenkins project and host the component on its infrastructure (if @rtyler is open to this option) 
* :whynotboth:

**Comment by rtyler** [comment]
If this is going to be built by Jenkins project infrastructure, this should be moved into the jenkinsci organization. Otherwise you're on your own

**Comment by oleg-nenashev** [comment]
Created #144 for AppVeyor
