### ISSUE TITLE
Update log4net packages to 2.0.latest

### ISSUE THREAD

**Issue by oleg-nenashev** [kohsuke/winsw#148]
It would effectively update log4net from `1.2.13` to `1.2.15`. There is no strongly related fixes, but it would be great to have the latest version.

See https://logging.apache.org/log4net/release/release-notes.html

**Comment by NextTurn** [comment]
@oleg-nenashev This is done.

**Comment by oleg-nenashev** [comment]
Yes, eons ago. https://github.com/kohsuke/winsw/commit/a8475e5dfa2e56c43ab7dc6dca07cb7d2cea4826
