### ISSUE TITLE
TimeSpan properties of the service description are being ignored. I have not been able to figure out why yet but the end result is that the default value is always used.

### ISSUE THREAD

**Issue by oleg-nenashev** [kohsuke/winsw#159]
It is a follow-up to the comment from @pkeusem  in #124

The proposed fix is:
> Prefixing the tagname with "//" in SingleTimeSpanElement() and replacing dom.FirstChild with dom in the SingleTimeSpanElement() invokes in WaitHint, SleepTime, ResetFailureAfter and StopTimeout resolves the problem of the waithint, sleeptime, resetfailure and stoptimeout config file property settings being ignored.

**Comment by pkeusem** [comment]
Here is a sample config.  The names have been changed to protect the guilty.

The .txt extension was added to enable attaching the file.


[WinService.xml.txt](https://github.com/kohsuke/winsw/files/676467/WinService.xml.txt)

**Comment by oleg-nenashev** [comment]
OK, will check it today. Maybe something like XML schema definition messes up the logic.

**Comment by oleg-nenashev** [comment]
OK, it seems to be fixed now. No similar pattern occurrences in other fields
