### ISSUE TITLE
V2 : `arguments` are not passed to the executable

### ISSUE THREAD

**Issue by sparqueur** [kohsuke/winsw#178]
Hello,

It seems that arguments are not passed when using winsw 2.
Everything works well with version 1.
[test.zip](https://github.com/kohsuke/winsw/files/684199/test.zip)
I attached an example to reproduce (unzip in C:\)

Thanks in advance

**Comment by oleg-nenashev** [comment]
Will check it ASAP

**Comment by oleg-nenashev** [comment]
Created the PR

**Comment by sparqueur** [comment]
Thx for bug fix.
When do you plan to do a new release ?

**Comment by oleg-nenashev** [comment]
@sparqueur Done. Release is rather click a button process now, so there is no problem to deliver fixes

**Comment by sparqueur** [comment]
Thx, everything seems to work well :)
