### ISSUE TITLE
why java '1.7' is required.not 1.7+

### ISSUE THREAD

**Issue by cxc3214** [kohsuke/winsw#190]
why
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

**Comment by oleg-nenashev** [comment]
@cxc3214 WinSW does not operate with Java itself. Whatever you mean, it is unlikely a WinSW issue

**Comment by cxc3214** [comment]
sorry,it's windows issue .

http://stackoverflow.com/questions/29697543/registry-key-error-java-version-has-value-1-8-but-1-7-is-required
