### ISSUE TITLE
Configuration to Limit Instance Running

### ISSUE THREAD

**Issue by yuska-y** [kohsuke/winsw#191]
How do I configure to limit only 1 instance running at any given time?

**Comment by oleg-nenashev** [comment]
Instance of what?
If you are talking about a Windows service, it always have only one instance running

**Comment by yuska-y** [comment]
The application, what my question is there's a config that can control and allow a given application to have a single invocation only, basically making sure that an application is not launched as a console application when running as a Windows Service or vice versa.

**Comment by oleg-nenashev** [comment]
No, there is no such config. And I am not sure if it doable at all without privilege escalation in Windows. If you need it, you would have to create a bootstrapper within your application.

**Comment by yuska-y** [comment]
@oleg-nenashev thank you very much for your clarification

**Comment by oleg-nenashev** [comment]
you are welcome
