### ISSUE TITLE
.net 2.0 and 3.0 base problem on newer windows

### ISSUE THREAD

**Issue by sachya** [kohsuke/winsw#200]
Hi, i am making an automated installer and use your executable to bind my application as service but sometimes on newer version of windows (more specifically windows 8 and 10), additional driver download creates hurdle.

The offline DISM method is very unreliable as it failed many times to work on certain pc and versions.

Can you provide me link for .net4 or higher versions as mentioned in readme?

**Comment by oleg-nenashev** [comment]
E.g. https://github.com/kohsuke/winsw/releases/download/winsw-v2.0.2/WinSW.NET4.exe
Now the .NET 4 - compatible executable is available for all release in GirHub and NuGet, though the code inside is still .NET2-compatible

**Comment by sachya** [comment]
Thanks, will check it today.
