### ISSUE TITLE
%BASE% relative path points to C:\windows\system32

### ISSUE THREAD

**Issue by drenda** [kohsuke/winsw#235]
Hi,
I'm using Spring boot like in this example https://github.com/snicoll-scratches/spring-boot-daemon
I was able to create and install the service.
I've a xml descriptor file like this:

`<service>
	<id>@dist.project.id@</id>
	<name>@dist.project.name@</name>
	<description>@dist.project.description@</description>
	<workingdirectory>%BASE%\</workingdirectory>
	<logpath>%BASE%\logs</logpath>
	<logmode>rotate</logmode>

	<executable>java</executable>
	<startargument>-Dspring.application.admin.enabled=true</startargument>
	<startargument>-Dcom.sun.management.jmxremote.port=@dist.jmx.port@</startargument>
	<startargument>-Dcom.sun.management.jmxremote.authenticate=false</startargument>
	<startargument>-Dcom.sun.management.jmxremote.ssl=false </startargument>
	<startargument>-cp</startargument>
	<startargument>lib/*</startargument>
	<startargument>net.nicoll.boot.daemon.StartSpringBootService</startargument>
	<startargument>@dist.start.class@</startargument>

	<stopexecutable>java</stopexecutable>
	<stopargument>-cp</stopargument>
	<stopargument>lib/*</stopargument>
	<stopargument>net.nicoll.boot.daemon.StopSpringBootService</stopargument>
	<stopargument>@dist.jmx.port@</stopargument>
</service>`

The problem is the relative path using %BASE%. Unfortunately when I try to start the service I've this exception:

`Impossibile avviare il servizio. System.IO.DirectoryNotFoundException: Impossibile trovare una parte del percorso 'C:\windows\system32\logs\spring-boot-daemon-sample.wrapper.log`

Seems the service is looking in the wrong folder. The folder with the service is in a subfolder of Documents of a user.

**Comment by oleg-nenashev** [comment]
Which version do you use in this case. If it is 1.9 like in #236, then it has to be checked on newer versions.

**Comment by drenda** [comment]
@oleg-nenashev With latest release this works fine. Thanks

**Comment by oleg-nenashev** [comment]
you are welcome
