### ISSUE TITLE
Maven artifact >1.9 doesn't work

### ISSUE THREAD

**Issue by drenda** [kohsuke/winsw#236]
I am using winsw with my Spring Boot application. I found the version 1.9 has some issue with this kind of configuration. Using the last version instead everything works fine. Unfortunately in maven repository (https://mvnrepository.com/artifact/com.sun.winsw/winsw) it works until the 1.9. The following releases are not working.

Could you fix that please? Thanks

**Comment by oleg-nenashev** [comment]
Please at least explain what does not work in your case.
Version 1.9 is 7 years old, newer versions are being successfully used in many projects.

**Comment by drenda** [comment]
@oleg-nenashev I don't think it's useful what doesn't work in my case with release 1.9 because - as you said - it's very old. With latest release my project works fine!

What I'm asking is to put new releases in maven repository because right now the last version you can use from maven is the 1.9.

This is the code you would add to pom.xml:

`
<dependency>
    <groupId>com.sun.winsw</groupId>
    <artifactId>winsw</artifactId>
    <version>2.1.0</version>
    <type>pom</type>
    <scope>provided</scope>
</dependency>
`
Unfortunately if you try to do that you have: `Failure to find com.sun.winsw:winsw:pom:2.1.0 `

I hope to clarified the problem. Thanks

**Comment by oleg-nenashev** [comment]
@drenda The latest version in Maven is 2.1.0: http://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/ . Probably you mean Maven Central, but it is not longer a release destination for WinSW. If you need it there, please create a ticket.

P.S: Generally I recommend to download binaries from NuGet or GitHub Release. They are being deployed for every release, Jenkins maven is legacy

**Comment by oleg-nenashev** [comment]
@drenda FYI I have deployed 2.1.2 to Jenkins Maven Repo

**Comment by drenda** [comment]
Thanks, I used that and everything is perfect. Very appreciated.
