### ISSUE TITLE
does not recursively kill child processes on exit

### ISSUE THREAD

**Issue by pnikonowicz** [kohsuke/winsw#246]
If a process that winSW wraps executes a child process, when winSW kills the wrapped process, the child process trees are not terminated. 

https://github.com/kohsuke/winsw/blob/master/src/Core/WinSWCore/Util/ProcessHelper.cs#L29
essentially calls to `(Get-WmiObject Win32_Process | where { $_.ParentProcessID -eq PROCESSID }).Name`

You can see that this does not execute recursively. 

Proposed fix is to traverse the process tree, killing each visited node during traversal

**Comment by oleg-nenashev** [comment]
It does kill processes recursively  iirc, but not all Windows tools have a valid process tree. E.g. cygwin
