### ISSUE TITLE
Service account password XML parsing issue

### ISSUE THREAD

**Issue by davestephens** [kohsuke/winsw#250]
A service account I use has an ampersand in its password, WinSW fails to parse the XML when running the `install` option. Given a service account block something like this (note the ampersand in the password field):
````
[snip]
  <serviceaccount>
    <domain>MYDOMAIN</domain>
    <user>svc-account-user</user>
    <password>T1r9_3&</password>
    <allowservicelogon>true</allowservicelogon>
  </serviceaccount>
[snip]
````
I get this error when running install:

````
System.Xml.XmlException: An error occurred while parsing EntityName. Line 28, position 22.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseEntityName()
   at System.Xml.XmlTextReaderImpl.ParseEntityReference()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at winsw.ServiceDescriptor..ctor()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
````

Removing the ampersand gets rid of the parsing error, but obviously my password is then wrong in the service configuration :)

Thanks in advance for any help!

**Comment by davestephens** [comment]
OK, so I've worked around this by replacing the & in the password with `&amp;`, but this feels a little opaque. Not sure if there's a better solution other than using a password without ampersands in?

**Comment by oleg-nenashev** [comment]
Well, WinSW configuration is a standard XML file: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
So you have to follow the standards in order to keep the file parseable.

Probably the documentation deserves a reference, but I do not consider it as a defect

**Comment by davestephens** [comment]
Documentation is fine, it'll help stop the 20 minutes or so of head scratching that followed the invalid XML error. 

Bear in mind a lot of people don't know the ins and outs of what is or isn't valid xml, given things like JSON or YML are generally favoured these days where these characters are perfectly valid. 

Also might be worth catching the error rather than dying with an XML parsing exception.

**Comment by oleg-nenashev** [comment]
> Bear in mind a lot of people don't know the ins and outs of what is or isn't valid xml, given things like JSON or YML are generally favoured these days where these characters are perfectly valid.

That's why WinSW should do XML validation (see #68). Switching to YAML is also an option, should be trivial to implement
