### ISSUE TITLE
Can you help write a xml config to run Nginx?

### ISSUE THREAD

**Issue by hailianghe** [kohsuke/winsw#253]
I want set Nginx as windows service, but i write some xml file,
it does not work all right, it can  add nginx to service, but can not start ...
Can you help me?

**Comment by hailianghe** [comment]
I use 2.1 version and solve this issue

**Comment by oleg-nenashev** [comment]
OK, thanks for the update!
Just to speed up the response next time, make sure you provide the version and at least startup logs (I will create an issue template)
