### ISSUE TITLE
How to reload configuration of nginx with winsw?

### ISSUE THREAD

**Issue by zchazc** [kohsuke/winsw#257]
Thank for you reading this question.
I wrapped nginx as a service with winsw,but when I reload it ,cmd reminded me :
nginx: [error] OpenEvent("Global\ngx_reload_4308") failed (5: Access is denied)

What happend?What should I begin?

**Comment by oleg-nenashev** [comment]
It seems to be an issue with Nginx permission management. Probably you could find a solution in this thread: https://forum.nginx.org/read.php?11,238513 (see the last post)

**Comment by zchazc** [comment]
Yes,it's an issue with Windows Service permission management.
I fixed it by set the service login as Administrator.
Thank you.
:)

**Comment by abghallab** [comment]
> Yes,it's an issue with Windows Service permission management.
> I fixed it by set the service login as Administrator.
> Thank you.
> :)

Thank you 
This solution worked for me

**Comment by manoharreddyporeddy** [comment]
Error:

    nginx: [error] OpenEvent("Global\ngx_reload_21428") failed (2: The system cannot find the file specified)

Reason:

    Due to a config error nginx exited.

Solution:

    The nginx was not running, started it.
