### ISSUE TITLE
Service installing error

### ISSUE THREAD

**Issue by Zhassulan** [kohsuke/winsw#260]
Hello! Tx! But i'm getting error when installing service via exe file. Application initialization error 0xc0000135. Env: Windows 7 x32 SP3.

**Comment by oleg-nenashev** [comment]
Likely it is caused by the missing >NET framework: https://stackoverflow.com/questions/11432940/what-does-error-code-0xc0000135-mean-when-starting-a-net-application
Please reopen if it's still actual
