### ISSUE TITLE
An executable for .NET Framework 4.5 

### ISSUE THREAD

**Issue by gzhu66** [kohsuke/winsw#268]
Is it possible for you to provide a WinSW executable for .NET Framework 4.5? Thanks so much

**Comment by oleg-nenashev** [comment]
Is anything wrong with a .NET4 executable? It runs well on my instances with new .NET versions

**Comment by gzhu66** [comment]
No, there is nothing wrong with .NET4 version when I run it on my desktop that's Windows 7. However, when running in the Windows 2012 server where there is .NET 4.5, when trying "MyApp.exe install", error popped up saying that "The following feature couldn't be installed: .NET Framework 3.5(includes .NET 2.0 and 3.0)"

So it seems to me that the executable version 2.1.2 needs
.NET framework 3.5, I could be wrong.

Thanks
Gary
On Feb 20, 2018, at 1:45 PM, Oleg Nenashev <notifications@github.com<mailto:notifications@github.com>> wrote:


Is anything wrong with a .NET4 executable? It runs well on my instances with new .NET versions

**Comment by gzhu66** [comment]
Thank you for your prompt response, I added the .exe configuration with <supportedRuntime version="v4.0"/> and that solved the problem.
