### ISSUE TITLE
Cannot start service of DebugViewPP

### ISSUE THREAD

**Issue by ritalin** [kohsuke/winsw#282]
I've been trying to make service for [DebugViewPP](https://github.com/CobaltFusion/DebugViewPP).

WinSw version is 2.1.2

Installing service was success.
But Cannot start service.

.err.log is
```
Unexpected error occurred: CreateDBWinBufferMapping
Another DebugView++ (or similar application) might be running. 
```

This message is printed when DebugViewPP is launched twice.
Actually, DebugViewPP  has rejected launching multiple process.

.out.log is
```
DebugViewConsole 1.8.0.7
Listening for OutputDebugString messages...
```
Looks like launching successfully once at leat.

.wrapper.log is
```
2018-06-25 16:19:59,971 INFO  - Starting (path-to)\DebugViewConsole.exe  -c -a 
2018-06-25 16:19:59,975 INFO  - Starting (path-to)\DebugViewConsole.exe  -c -a 
2018-06-25 16:19:59,986 INFO  - Started process 12548
2018-06-25 16:19:59,992 DEBUG - Forwarding logs of the process System.Diagnostics.Process (DebugViewConsole) to winsw.RollingLogAppender
```

Looks like starting twice...

any idea?

thanks.

**Comment by ritalin** [comment]
Configuration file is
```
<service>
  <id>My_LogAgent</id>
  <name>Debug Log Agent (powered by WinSW)</name>
  <description>....</description>
  <logpath>%BASE%\logs</logpath>
  <logmode>roll</logmode>
  <depend></depend>
  <executable>%BASE%\DebugViewConsole.exe</executable>
  <startargument>-c</startargument>
  <startargument>-a</startargument>
</service>

```

**Comment by ritalin** [comment]
Sorry, my environment is
* Windows 10 (version 1803)
* Installed .NET Framework is 2.0, 3.0, 3.5 and 4.0.

**Comment by oleg-nenashev** [comment]
Maybe it is caused by a combination of `executable` and `startargument`. Would it be possible to try `argument` instead?

**Comment by ritalin** [comment]
Thunks @oleg-nenashev 

Using **argument** has no effect...

**Comment by ritalin** [comment]
Staring service twice in wrapper.log is logs before and after loading extensions.

**At the consequence, WinSw has no problem.**

This error is due to shared memory management in DebugViewPP.
Shared memory in service has dark deeply.
This problem can not be resolved briefly...

**Comment by Roman-Bober** [comment]
having same error, when running DebugViewPP Console exe , spawning it from C# code as child process. with args
