### ISSUE TITLE
return code of -2148734720 when install is run

### ISSUE THREAD

**Issue by mark-russell-bossanova** [kohsuke/winsw#284]
I have an ansible script that is staring a windows slave to connect via JNLP.  

I follow followed all of the instructions here to set up the winsw

- copied the executable from http://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/2.1.2/winsw-2.1.2-bin.exe
- renamed it to `run_slave.exe`
- template the xml file 
```
<configuration>
    <id>jenkins_slave</id>
    <name>Jenkins Slave</name>
    <description>Jenkins Slave JNLP service</description>
    <executable>java</executable>
    <arguments>-jar F:\data\jenkins\agent\agent.jar -jnlpUrl http://x.x.x.x:8080/computer/jslave-win-fw-0/slave-agent.jnlp -secret xxxx -workDir f:\data\jenkins -auth jenkins:yyyy</arguments>
    <onfailure action="restart" delay="20 sec"/>
    <resetfailure>1 hour</resetfailure>
    <logpath>F:\data\jenkins\agent\logs</logpath>
    <log mode="roll-by-time">
        <pattern>yyyyMMdd</pattern>
    </log>
</configuration>
```
- when I run this in ansible I get a return code of 2148734720 but if run it in powershell I get -2148734720

Any suggestion on how to get this to run or to get nor debugging.  I also get no logs.

I am running this on a Microsoft Azure machine.

**Comment by mark-russell-bossanova** [comment]
It turns out that I downloaded the wrong file.  I should have downloaded https://github.com/kohsuke/winsw/releases/download/winsw-v2.1.2/WinSW.NET4.exe.  All is working now.  This can be closed

**Comment by oleg-nenashev** [comment]
thanks for the update!
