### ISSUE TITLE
100% CPU usage on stopping of service

### ISSUE THREAD

**Issue by gverran** [kohsuke/winsw#31]
Hi there

I am using winsw to enable nginx to be started and stopped as a Windows Service.  

After I configured everything under 1.9 - since all the tutorials online referred to 1.9 - I managed to start and stop a service successfully.  I also checked that the nginx.exe processes were absent on stopping of the service.  All was happy!

I then migrated to 1.14 and after having to make some configuration changes to work around a possible bug as already logged 7 months ago (https://github.com/kohsuke/winsw/issues/24) and changing the logging parameters, I got the service to start, but when I hit stop, the service did not stop and my CPU usage jumped to 100%.  I also added the stoptimeout as a fallback, but that didn't even kick in.  I had to kill the 2x nginx.exe processes.

I am running this under Windows XP SP3.

I have already established that this isn't an nginx issue since this worked perfectly under 1.9.

kohsuke please advise and if you can provide a fix in the next version and when that version will be available?

Here is my configuration file.

```
<service>
  <id>Nginx</id>
  <name>Nginx</name>
  <description>Nginx</description>
  <executable>E:/comp/nginx/nginx.exe</executable>
  <logpath>E:/comp/nginx/logs/</logpath>
  <log mode="roll-by-size">
    <sizeThreshold>10240</sizeThreshold>
    <keepFiles>8</keepFiles>  
  </log>
  <workingdirectory>E:/comp/nginx</workingdirectory>
  <startargument></startargument>
  <stopexecutable>E:/comp/nginx/nginx.exe</stopexecutable>
  <stopargument>-s quit</stopargument>
  <stoptimeout>10sec</stoptimeout>
</service>
```

**Comment by oleg-nenashev** [comment]
@gverran 
Could you confirm the issue for the latest winsw version?

**Comment by kohsuke** [comment]
No further input from the reporter. Closing this out.
