### ISSUE TITLE
not able to execute groovy 

### ISSUE THREAD

**Issue by Bhimreddy** [kohsuke/winsw#322]
Hi,

i have created a windows service for my jar using Winsw, my jar internally executes a groovy script. but after creating windows service its unable to execute groovy. whenever it reaches to the groovy part it just hangs there.  please help me to solve this issue.

Regards,
Bhimreddy

**Comment by oleg-nenashev** [comment]
It is not possible to say anything without knowing your WinSW configuration, Java version, Groovy code, and a platform.

Most likely it is an issue in your setup. Please feel free to reopen once you can provide the information above

**Comment by Bhimreddy** [comment]
Thanks for the quick response, 
Java Version : 1.8
platform: windows server 2012R2

Configuration : <configuration>
  
  
  <id>rc-TPP-Interface</id>
  
  <name>_TPP_Interface</name>
  
  <description>Request Creation</description>
  
  
  <executable>java</executable>
  <arguments>-jar %BASE%\TPP_Interface-5.12.jar</arguments>
</configuration>
 
Groovy code : Okey there was a mistake, actually in my cod (jar) it calls a batch file which internally executes groovy, but when we run this batch file it hangs.

batch file : 
@echo off
rem Copyright 2016 Palamida Inc., All Rights Reserved.
rem
rem This software is the confidential property of Palamida, Inc.
rem

if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.\
set APPDIR=%DIRNAME%..

:setOps
if not "%PAL_SCRIPT_MAX_HEAP_MB%" == "" goto setHeap
set PAL_SCRIPT_MAX_HEAP_MB=1024

:setHeap
if not "%JAVA_OPTS%" == "" goto haveJavaOpts
set JAVA_OPTS=-Xms64m -Xmx%PAL_SCRIPT_MAX_HEAP_MB%m

:haveJavaOpts
@REM ==== START VALIDATION ====
if exist "%HOME%\.palamida\scriptRunner_pre.bat" call "%HOME%\.palamida\scriptRunner_pre.bat"

if "%PAL_JAVA_HOME%" == "" goto needJava
goto haveJava

:needJava
if not "%JAVA_HOME%" == "" goto OkJHome
echo Either PAL_JAVA_HOME or JAVA_HOME must be defined to point to the JDK used by Palamida.
goto end

:OkJHome
set PAL_JAVA_HOME=%JAVA_HOME%

:haveJava
if exist "%PAL_JAVA_HOME%\bin\java.exe" goto checkToolsJar
echo Cannot launch scriptRunner: %PAL_JAVA_HOME%\bin\java.exe does not exist.
goto end

:checkToolsJar
if exist "%PAL_JAVA_HOME%\lib\tools.jar" goto runIt
echo Cannot launch scriptRunner: %PAL_JAVA_HOME%\lib\tools.jar does not exist.
goto end

:runIt
set GROOVY_CONF=%APPDIR%\conf\scriptRunner.conf
rem set JAVA_OPTS=%JAVA_OPTS% -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5010
set JAVA_OPTS=%JAVA_OPTS% -DprogramName=ScriptRunner
set JAVA_OPTS=%JAVA_OPTS% -Dgroovy.home="%APPDIR%"
set JAVA_OPTS=%JAVA_OPTS% -Dscript.runner.home="%APPDIR%"
set JAVA_OPTS=%JAVA_OPTS% -Dtools.jar="%PAL_JAVA_HOME%\lib\tools.jar"
set JAVA_OPTS=%JAVA_OPTS% -Dgroovy.starter.conf="%GROOVY_CONF%"
set JAVA_OPTS=%JAVA_OPTS% -Dpalamida.ssl=false
"%PAL_JAVA_HOME%\bin\java.exe" %JAVA_OPTS% -cp "%APPDIR%\lib\groovy-all-1.5.4.jar" org.codehaus.groovy.tools.GroovyStarter --main com.palamida.script.ScriptRunner --conf "%GROOVY_CONF%" %*
goto end


:end
if "%OS%"=="Windows_NT" endlocal
