### ISSUE TITLE
服务无法启动-发生系统错误1067

### ISSUE THREAD

**Issue by qq122716072** [kohsuke/winsw#325]
win10家庭版 ,
![image](https://user-images.githubusercontent.com/16949869/59649189-610ea000-91b4-11e9-86b2-757b51f31f55.png)

**Comment by qq122716072** [comment]
发生系统错误1067

**Comment by qq122716072** [comment]
windows logs:
![image](https://user-images.githubusercontent.com/16949869/59650859-24de3e00-91ba-11e9-9d88-e2aaaf530dae.png)

**Comment by oleg-nenashev** [comment]
Please resubmit the report in English

**Comment by JianfeiMa** [comment]
on main method add this code ->
while (true) {
            try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

**Comment by NextTurn** [comment]
Tracked by #396
