### ISSUE TITLE
winsw 1.14 for nginx.exe - can't stop service

### ISSUE THREAD

**Issue by tonyschwartz** [kohsuke/winsw#33]
Hello,

I'm trying to use winsw 1.14 to wrap nginx.exe.  It works great except for one thing.  I cannot get the service to stop properly.

Here is my winsw configuration:

&lt;service&gt;<br/>  &lt;id&gt;nginx&lt;/id&gt;<br/>  &lt;name&gt;nginx&lt;/name&gt;<br/>  &lt;description&gt;nginx service&lt;/description&gt;<br/>  &lt;executable&gt;d:\prog\nginx\1.5.12.2\nginx.exe&lt;/executable&gt;<br/>  &lt;startargument&gt;-p&lt;/startargument&gt;<br/>  &lt;startargument&gt;d:\prog\nginx\1.5.12.2&lt;/startargument&gt;<br/>  &lt;startargument&gt;-c&lt;/startargument&gt;<br/>  &lt;startargument&gt;conf\nginx.conf&lt;/startargument&gt;<br/>  &lt;stopargument&gt;-p&lt;/stopargument&gt;<br/>  &lt;stopargument&gt;d:\prog\nginx\1.5.12.2&lt;/stopargument&gt;<br/>  &lt;stopargument&gt;-s&lt;/stopargument&gt;<br/>  &lt;stopargument&gt;stop&lt;/stopargument&gt;<br/>  &lt;logmode&gt;rotate&lt;/logmode&gt;<br/>  &lt;logpath&gt;D:\Bin\logs\nginx&lt;/logpath&gt;<br/>  &lt;workingdirectory&gt;d:\prog\nginx\1.5.12.2&lt;/workingdirectory&gt;<br/>&lt;/service&gt;

When I stop the service in windows 7, the service appears stopped, but if I look at the task manager, I still see nginxsvc.exe and both nginx.exe processes.  I then I have to terminate the processes manually.  Just wondering if you know why or how I can get around this?

Thanks for your help.  This is a great app.

**Comment by janzz11** [comment]
Hello,
I tried it your way, but there was no way to stop the service. The error message showed that the service didn't respond to the start-up or control request in time.
Here is my winsw configuration:
<service>
  <id>Nginx-8161-web</id>
  <name>Nginx-8161-web</name>
  <description>Nginx-8161-web</description>
  <executable>E:\nginx-1.12.2\nginx.exe</executable>
  <logpath>E:\nginx-1.12.2\logs\</logpath>
  <logmode>roll</logmode>
  <depend></depend>
  <stopexecutable>E:\nginx-1.12.2\nginx.exe</stopexecutable>
<startargument> -p </startargument> 
<startargument> E:\nginx-1.12.2 </startargument> 
<startargument>-c</startargument> 
<startargument>conf\nginx-8161-web.conf</startargument> 
<stopargument>-p</stopargument> 
<stopargument>E:\nginx-1.12.2</stopargument> 
<stopargument>-s</stopargument> 
<stopargument>stop</stopargument> 
<workingdirectory>E:\nginx-1.12.2</workingdirectory> 
</service>

If I run according to the following configuration
<?xml version="1.0" encoding="UTF-8" ?>
<service>
  <id>Nginx-8161-web</id>
  <name>Nginx-8161-web</name>
  <description>Nginx-8161-web</description>
  <executable>E:\nginx-1.12.2\nginx.exe</executable>
  <logpath>E:\nginx-1.12.2\logs\</logpath>
  <logmode>roll</logmode>
  <depend></depend>
  <startargument>-p E:\nginx-1.12.2</startargument>
  <startargument>-c \conf\nginx-8161-web.conf</startargument>
  <stopexecutable>E:\nginx-1.12.2\nginx.exe -s stop</stopexecutable>
</service>
It can stop service, but it just killed a process in nginx.exe.
Is there any problem with grammar written by me? Or why?

**Comment by oleg-nenashev** [comment]
Anyway, please make sure to update to WinSW 2.x

**Comment by janzz11** [comment]
I use the winsw-v2.1.2 version, but there will be no service startup. The wrong log information is shown below
nginx: [alert] could not open error log file: CreateFile() " E:\nginx-1.12.2/logs/error.log" failed (123: The filename, directory name, or volume label syntax is incorrect)
2018/08/28 16:42:42 [emerg] 3020#2920: CreateFile() " E:\nginx-1.12.2/ \conf\nginx-8161-web.conf" failed (123: The filename, directory name, or volume label syntax is incorrect)
Here is my winsw configuration:
[nginx-8161-web.txt](https://github.com/kohsuke/winsw/files/2327232/nginx-8161-web.txt)
I don't know where problems is
