### ISSUE TITLE
Enable TLS 1.1 /1.2 support on Windows versions which support it

### ISSUE THREAD

**Issue by dschoeneborn** [kohsuke/winsw#337]
Hi we would like to download a jar file from a https secured server. However, the server does not support TLS 1.0, only TLS 1.1 upwards.

Since WINSW does not support TLS 1.1, 1.2 and 1.3 with .Net4.0, we cannot realize our project. 

My question: would you provide a version that supports newer TLS versions (i.e. with .Net 4.5)? That would help us incredibly.

**Comment by dschoeneborn** [comment]
I took a look at the source code. But since the download functionality is implemented in the core project, which still runs on .Net 2.0, I don't think I'm able to port it.

I hope that a nice guy, with more knowledge, will do this.

**Comment by dschoeneborn** [comment]
Ok, maybe I've already found the solution.
This article describes that .Net 2.0 has implemented TLS 1.2 after a certain hotfix. 
https://support.microsoft.com/en-us/help/3154518/support-for-tls-system-default-versions-included-in-the-net-framework

To activate TLS 1.2 the following classes have to be added to the WinSWCore project:

```
SecurityProtocolTypeExtensions.cs
namespace System.Net
{
using System.Security.Authentication;
public static class SecurityProtocolTypeExtensions
{
public const SecurityProtocolType Tls12 = (SecurityProtocolType)SslProtocolsExtensions.Tls12;
public const SecurityProtocolType Tls11 = (SecurityProtocolType)SslProtocolsExtensions.Tls11;
public const SecurityProtocolType SystemDefault = (SecurityProtocolType)0;
}
} 
SslProtocolsExtensions.cs
namespace System.Security.Authentication
{
public static class SslProtocolsExtensions
{
public const SslProtocols Tls12 = (SslProtocols)0x00000C00;
public const SslProtocols Tls11 = (SslProtocols)0x00000300;
}
}
```

Then the command `System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolTypeExtensions.Tls12;` must be called somewhere in the application.

Then I rebuilt the solution and it worked.

**Comment by oleg-nenashev** [comment]
We would still need to bump the minimal supported OS to enable this solution. `TLS v1.1 and v1.2 are not available in Windows Vista or Windows Server 2008.`. It is not that I am against doing so, quite opposite actually. Probably we could just put the code within the OS version check block.

**Comment by oleg-nenashev** [comment]
I'd guess now the recommendation is to proceed with the .NET 4.6.1 or .NET Core binaries provided by @NextTurn in 2.4.0. https://github.com/kohsuke/winsw/releases/tag/winsw-v2.4.0 . I will create a follow-up task to document it
