### ISSUE TITLE
How to use Jconsole monitor wrapper java service

### ISSUE THREAD

**Issue by Neii** [kohsuke/winsw#342]
my project running  with win32 jdk 1.8.0_112 on windows server 2008 R2, Follow the guidelines wrapper service in running well,i want monitor my project jvm process heap with jdk tool 'jconsole'/'jvisualvm',  but i can't found jvm process instance in these tools GUI, on windows task manager i can find jvm process instance PID,but can't use it with command,like 'jconsole PID' is not working,what did i do wrong...
ps:i try use 'com.sun.management.jmxremote.port' and 'java.rmi.server.hostname' property in config xml like this 
`<service>
    <id>myproject</id>
    <name>myproject</name>
    <description>This runs Spring Boot as a Service.</description>
    <executable>java</executable>
    <arguments>-Xmx1024m -jar "myproject-1.4.jar" -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1111-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=1.1.1.1</arguments>
    <logmode>rotate</logmode>
</service>`
but is not working too

**Comment by jvmlet** [comment]
@Neii , please see https://github.com/kohsuke/winsw/issues/150, might be relevant

**Comment by Neii** [comment]
@jvmlet ,thanks a lot,i will try it.
