### ISSUE TITLE
Service won't start if 'install' command is run from a different directory

### ISSUE THREAD

**Issue by pbitty** [kohsuke/winsw#36]
It seems that if you run `winsw.exe install` from outside the directory where it is located, you get an error when trying to start the service.

Example:

With this directory structure:
```
c:\app\
c:\app\service\winsw.exe
c:\app\service\winsw.xml
```

And this `winsw.xml` file:
```xml
<service>
  <id>app</id>
  <name>app</name>
  <description>app</description>
  <executable>cmd</executable>
  <arguments>/D /C ping -t localhost</arguments>
</service>
```

If I install the service from I outside the directory: 
```
C:\app>service\winsw.exe install
``` 
and I try to start it: 
```
C:\app>service\winsw.exe start
```

I get this error:
```
WMI.WmiException: UnknownFailure
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServiceProxy.StartService()
   at winsw.WrapperService.Run(String[] _args)
   at winsw.WrapperService.Main(String[] args)
```

If install it from its own folder: 
```C:\app\service>winsw.exe install```

I can run `winsw.exe start` from any folder and the service will start just fine.

Here's my windows info:
```
OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601
```

Thanks for making such a useful tool!

**Comment by mafia23** [comment]
H:\push\ROOT_8283_2>ROOT.exe install
2019-07-05 09:07:31,354 INFO  - Installing the service with id 'ROOT_8283_2'

H:\push\ROOT_8283_2>ROOT.exe start
2019-07-05 09:09:31,700 INFO  - Starting the service with id 'ROOT_8283_2'
2019-07-05 09:09:31,760 FATAL - WMI Operation failure: PathNotFound
WMI.WmiException: PathNotFound
   在 WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   在 WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object
[] args)
   在 WMI.Win32ServiceProxy.StartService()
   在 winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   在 winsw.WrapperService.Main(String[] args)
WMI.WmiException: PathNotFound
   在 WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   在 WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object
[] args)
   在 WMI.Win32ServiceProxy.StartService()
   在 winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   在 winsw.WrapperService.Main(String[] args)

How can  I fix this?
