### ISSUE TITLE
XML file name (file not found error)

### ISSUE THREAD

**Issue by moorecode** [kohsuke/winsw#388]
As I understand it, the `winsm.exe` file, when renamed will look for an `xml` file with a matching name? I have renamed mine to `program.exe` and I have my config in `program.xml` but when I try `program.exe install` I get a file not found error, as it is searching for `WindowsService.xml` not `program.xml`. Am I assuming the wrong thing? If the config has to be called `WindowsService.xml` then how can I have multiple services in the same directory?

EDIT: 
I have also tried to rename it to `WindowsService.xml` and the program still cannot find it, what am I doing wrong?

**Comment by NextTurn** [comment]
Please don't use WinSW 2.4.0 on .NET Core. It's not ready for release. Use NET4/NET461 editions instead.

**Comment by moorecode** [comment]
Fixed. Thanks!

**Comment by NextTurn** [comment]
This will be fixed in the next version. Thanks for the report.
