### ISSUE TITLE
Service not installed with 4.61

### ISSUE THREAD

**Issue by Martin-Locker** [kohsuke/winsw#419]
We start an install command from pwershell script. With version 4.5.0.

After call install there is only one output: 

"Starting WinSW in the service mode".

With 4.50 the output is: 

"Starting ServiceWrapper in the CLI mode
Installing the service with id 'ServiceName'
Completed. Exit code is 0"

Windows Server 2016 (all installed security patches of week 7/2020)
NET Framework 4.0

**Comment by NextTurn** [comment]
Is it a non-interactive PowerShell session?

**Comment by Martin-Locker** [comment]
It's non-interactive.
If I log on the servier and tests the command in powershell it works with 4.6.1 too.
The log output ist than "Starting ServiceWrapper in the CLI mode" instead "service mode".
