### ISSUE TITLE
The current post-build steps should be optional

### ISSUE THREAD

**Issue by alexandrul** [kohsuke/winsw#5]
It would be nice to build the project without requiring any changes. The current post-build steps must be removed in order to build the project.

Is there a way to configure the project to run the current post-build steps only if they are desired? (like detecting the presence of a .cmd file, and providing a .cmd.sample one)

**Comment by oleg-nenashev** [comment]
The issue will be fixed in https://github.com/kohsuke/winsw/pull/62
