### ISSUE TITLE
Disable logging of (specific) environment variables (or mask values) in Windows 'Application' event log

### ISSUE THREAD

**Issue by kenny-evitt** [kohsuke/winsw#54]
I was investigating #52 and discovered that all of the environment variables, and their values, are logged in the Windows _Application_ event log, in plaintext.

Based on [this](http://blogs.msdn.com/b/ericfitz/archive/2006/03/01/default-acls-on-windows-event-logs.aspx), every interactive user has read+write access to that event log.

I'm currently using environment variables to store all of my application's runtime environment-specific configuration, e.g. database credentials. I'm not particularly worried that they will be compromised as-is, but it would be much better were this info to not be included in the event log in plaintext.

It would fine if an attribute could be added or set on the `env` elements in the configuration file to indicate that the value for those variables not be included (or even just masked) in the event log.

**Comment by oleg-nenashev** [comment]
It makes sense to handle this case in winsw-2.0 with log4net (#72)

**Comment by oleg-nenashev** [comment]
In #154 I've clarified the behavior of this option.
Maybe makes sense to disable the wrapper log as well, but likely it needs to be a separate option in order to retain the backward compatibility

**Comment by kenny-evitt** [comment]
@oleg-nenashev Fantastic! I'll test this when I get a chance; hopefully within a month or two.
