### ISSUE TITLE
Define a new MVS version to be used in the project

### ISSUE THREAD

**Issue by oleg-nenashev** [kohsuke/winsw#56]
MVS2008 is quite outdated. For the sake of compatibility of solution files, it makes sense to use MVS2010 or greater

**Comment by oleg-nenashev** [comment]
@kohsuke 
Any decisions/plans? It would be great to release a new version with bugfixes.

In #42 @mpdeimos proposed to use MVS2013 due to its availability for FOSS projects.

**Comment by mpdeimos** [comment]
Here is the link to the free VS 2013 offer for FOSS projects:
http://www.visualstudio.com/en-us/products/free-developer-offers-vs

**Comment by oleg-nenashev** [comment]
We agreed to use MVS2013 Community Edition
See the discussion here http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-01-21-19.01.log.html

**Comment by oleg-nenashev** [comment]
Closing the issue. PR has been created
