### ISSUE TITLE
BSOD after service restart

### ISSUE THREAD

**Issue by killerswan** [kohsuke/winsw#57]
After running `my-service-winsw.exe restart` (winsw-1.16 for a Python service), I got this BSOD:
![bsod](https://cloud.githubusercontent.com/assets/195060/5152242/d7c2cfb4-71a2-11e4-8398-8beb7dffcac4.png)

Has anybody seen a thing like this?  I've got Windows Server 2008 R2 (64-bit)...

**Comment by oleg-nenashev** [comment]
@killerswan 
Unfortunately, I cannot provide symbols for winsw-1.16

Will you be able to re-test your case on winsw-1.17?
You can find the beta version and symbols in https://github.com/kohsuke/winsw/releases/tag/1.17-beta

**Comment by oleg-nenashev** [comment]
winsw-1.17-beta.2 is also available for the testing.
https://github.com/kohsuke/winsw/releases/tag/1.17-beta.2

**Comment by killerswan** [comment]
I've just seen another BSOD, and so now upgraded to 1.17 beta 2, now, so I'll report back if anything odd happens with that build!

**Comment by oldmud0** [comment]
Maybe PID 0 is being killed?

**Comment by oleg-nenashev** [comment]
Seems it has not happened again. Feel free to reopen if somebody hits the issue
