### ISSUE TITLE
How to debug service failing to start

### ISSUE THREAD

**Issue by pvandervelde** [kohsuke/winsw#60]
I'm using winsw to run jenkins as a service. However for some reason the service will not start, or more accurately it starts and immediately stops. The eventlog only tells me that the service stopped but not why it stopped. No log files are produced in the jenkins directory (where the winsw.exe lives). Unfortunately this is on a production machine so no visual studio available either :(

Any suggestions on how to figure out why the service isn't starting? I'm assuming there's something wrong with either the service installation / setup or the configuration file because starting jenkins from the command line works just fine.

**Comment by oleg-nenashev** [comment]
@pvandervelde 
WinSW puts the most of the messages to Windows system logs.
If you don't see anything there, most probably the service cannot be initialized due to missing credentials or permissions.

**Comment by oleg-nenashev** [comment]
Seems you've already investigated your issue in #61

**Comment by pvandervelde** [comment]
Yeah I did. I should have made a note. Thanks for reminding me.
