### ISSUE TITLE
Create & publish NuGet package for WinSW

### ISSUE THREAD

**Issue by oleg-nenashev** [kohsuke/winsw#65]
For .NET projects NuGet is a preferable package manager.
It would be great to support this repository together with Maven

**Comment by kenmaglio** [comment]
If you look at Chocolatey for Business -- it has a very easy simplistic package creator. You can even try it out for a while too (full featured).

**Comment by oleg-nenashev** [comment]
@kenmaglio I do not consider enterprise tools for the build flow

**Comment by oleg-nenashev** [comment]
So, it is here: https://www.nuget.org/packages/WinSW/
