### ISSUE TITLE
Maven Build flow should pick releases from GitHub or NuGet

### ISSUE THREAD

**Issue by oleg-nenashev** [kohsuke/winsw#80]
A correct Assembly version is required to track dependencies and to show it in CLI.

TODOs:
- Manually fix the version for winsw-1.x
- Adjust build flows to check/update Assembly info and pow.xml

Required for #78

**Comment by oleg-nenashev** [comment]
The bug has been fixed in winsw-1.17
For winsw-2.0 it's just an improvement case

**Comment by mrjoel** [comment]
This was updated for 1.18, however the 1.19 release still misreports 1.18 as the assembly version...

**Comment by oleg-nenashev** [comment]
Fixed in 2.19.1 BTW it's still a risk

**Comment by oleg-nenashev** [comment]
So the new flow has been merged. Maven release attempts will fail if the version differs from the WinSW release
