### ISSUE TITLE
Annotate system/plugin API

### ISSUE THREAD

**Issue by oleg-nenashev** [kohsuke/winsw#88]
- https://www.nuget.org/packages/JetBrains.Annotations/ will be useful to get <code>@Nonnull</code> and <code>@CheckForNull</code> annotations
- other annotations like <code>@Extension</code> could be useful for extensions engine

**Comment by kbrimble** [comment]
Hi @oleg-nenashev, I've looked into this issue but I can't see any example where these attributes would be helpful. Is there somewhere specific that you had in mind?

**Comment by oleg-nenashev** [comment]
It's only for Static analysis, no user-visible impact.

**Comment by kbrimble** [comment]
Yeah of course. I just couldn't see anywhere in the code where these
annotations could be applied.

**Comment by oleg-nenashev** [comment]
Well, there were already bug reports regarding NPEs. For the current codebase I agree that it's not that risky

**Comment by kbrimble** [comment]
Do you have a specific place where the Null References are being thrown
that I could take a look at?

**Comment by oleg-nenashev** [comment]
Well, it's mostly for null checks and missing exception handling. Nothing really urgent anyway
